name: PR

on:
  pull_request:
    branches: [ main ]

jobs:

  pr:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '318.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - run: gcloud projects list
