name: PR

on:
  pull_request:
    branches: [ main ]

env:
  GCP_REGION: europe-west1
  GCP_COMPOSER_ENV_NAME: airflow-demo

jobs:

  pr:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Test DAGs
        run: |-
          python -V
          pip install pytest
          pytest

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '318.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Deploy DAGs
        run: |-
          COMPOSER_BUCKET=$(gcloud composer environments describe $GCP_COMPOSER_ENV_NAME \
            --location $GCP_REGION \
            --format="get(config.dagGcsPrefix)")

          echo $COMPOSER_BUCKET
      