name: PR

on:
  pull_request:
    branches: [ main ]

env:
  GCP_REGION: europe-west1
  GCP_COMPOSER_ENV_NAME: airflow-demo

jobs:

  pr:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'


      - name: Set up more dependencies 
        run: |-
          python -V
          pip install pytest
          pip install flake8

          mkdir -p output/

      - name: Python Static Analysis
        run: |-
          echo "\`\`\`bash" > output/test_results.txt
          
          flake8 --tee --output-file=output/test_results.txt dags/

          echo "\`\`\`" >> output/test_results.txt

      - name: Python Unit Tests
        run: |-
          echo "\`\`\`bash" > output/test_results.txt

          pytest | tee -a output/test_results.txt

          echo "\`\`\`" >> output/test_results.txt

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '318.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Integration Tests
        run: |-

          echo "\`\`\`bash" > output/test_results.txt

          test_dags_path=/home/airflow/gcs/data/test-dags/${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}/

          gsutil -m cp ./dags $test_dags_path

          gcloud composer environments run $GCP_COMPOSER_ENV_NAME \
            --location $GCP_REGION \
            list_dags -- -sd $test_dags_path

          echo "\`\`\`" >> output/test_results.txt

      - name: Comment PR
        uses: machine-learning-apps/pr-comment@master
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: output/test_results.txt